<?php
$array=array("2024" => array(
  "01" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "11.7","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "11.7","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "11.9","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "10.47","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "9.36","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "14.9","extra" => "0"),
                //array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "30.8","extra" => "11.7"),
                array("company" => "sendle","product" => "sendle","fuel" => "11.5","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
            ),
  "02" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "9.7","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "9.7","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "10.6","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "9.92","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "9.26","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "14.75","extra" => "0"),
                //array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "28.6","extra" => "10.1"),
                array("company" => "sendle","product" => "sendle","fuel" => "9.7","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
  ),
    "03" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "8","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "8","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "9.3","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "10.6","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "10.73","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "17.09","extra" => "0"),
                //array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "27.6","extra" => "9.5"),
                array("company" => "sendle","product" => "sendle","fuel" => "9","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "21","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
    ),
     "04" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "7.7","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "7.7","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "8.8","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "9.92","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "9.26","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "14.75","extra" => "0"),
                //array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "28.6","extra" => "10.1"),
                array("company" => "sendle","product" => "sendle","fuel" => "9.7","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
     ),
     "05" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "8.8","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "8.8","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "8.9","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "10.82","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "10.4","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "16.56","extra" => "0"),
                //array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "28.7","extra" => "9.7"),
                array("company" => "sendle","product" => "sendle","fuel" => "8.8","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
    ),
     "05" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "8.8","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "8.8","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "8.9","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "10.82","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "10.4","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "16.56","extra" => "0"),
                //array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "28.7","extra" => "9.7"),
                array("company" => "sendle","product" => "sendle","fuel" => "8.8","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
    ),
     "06" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "8.3","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "8.3","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "8.8","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "10.32","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "9.42","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "15.01","extra" => "0"),
                //array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "31.4","extra" => "10.2"),
                array("company" => "sendle","product" => "sendle","fuel" => "9","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
    ),
     "07" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "7.4","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "7.4","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "9.7","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "10.32","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "9.42","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "15.01","extra" => "0"),
                array("company" => "oc","product" => "ocep","fuel" => "0","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "30.5","extra" => "9.7"),
                array("company" => "sendle","product" => "sendle","fuel" => "9","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
    ),
     "08" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "7.3","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "7.3","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "9","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "9.82","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "9.55","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "15.2","extra" => "0"),
                array("company" => "oc","product" => "ocep","fuel" => "0","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "29.5","extra" => "9"),
                array("company" => "sendle","product" => "sendle","fuel" => "8.8","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
    ),
    "09" =>array(
               array("company" => "australia_post","product" => "australia_post","fuel" => "7.4","extra" => "0"),
               array("company" => "australia_post","product" => "startrack","fuel" => "7.4","extra" => "0"),
               array("company" => "aramex","product" => "myfastway","fuel" => "8.6","extra" => "0"),
               array("company" => "toll","product" => "priority","fuel" => "10.82","extra" => "0"),
               array("company" => "toll","product" => "ipec","fuel" => "10.4","extra" => "0"),
               array("company" => "toll","product" => "pallets","fuel" => "16.56","extra" => "0"),
               array("company" => "oc","product" => "ocep","fuel" => "0","extra" => "0"),
               array("company" => "couriers_please","product" => "couriers_please","fuel" => "28.7","extra" => "9.7"),
               array("company" => "sendle","product" => "sendle","fuel" => "8.8","extra" => "0"),
               array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
               array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
               array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
               array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
               array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
   )	
   ,
     "10" =>array(
                array("company" => "australia_post","product" => "australia_post","fuel" => "7.3","extra" => "0"),
                array("company" => "australia_post","product" => "startrack","fuel" => "7.3","extra" => "0"),
                array("company" => "aramex","product" => "myfastway","fuel" => "8.9","extra" => "0"),
                array("company" => "toll","product" => "priority","fuel" => "10.82","extra" => "0"),
                array("company" => "toll","product" => "ipec","fuel" => "10.4","extra" => "0"),
                array("company" => "toll","product" => "pallets","fuel" => "16.56","extra" => "0"),
                array("company" => "oc","product" => "ocep","fuel" => "0","extra" => "0"),
                array("company" => "couriers_please","product" => "couriers_please","fuel" => "28.7","extra" => "9.7"),
                array("company" => "sendle","product" => "sendle","fuel" => "8.8","extra" => "0"),
                array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "21.1"),
                array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                array("company" => "border_express","product" => "border_express","fuel" => "23","extra" => "0"),
                array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
    )		
  )		

);



echo json_encode($array);
