 $array=array("2022"=>
            array(
                "08" =>array(
                    array("company" => "australia_post","product" => "australia_post","fuel" => "9","extra" => "0"),
                    array("company" => "australia_post","product" => "startrack","fuel" => "9","extra" => "0"),
                    array("company" => "aramex","product" => "myfastway","fuel" => "9.6","extra" => "0"),
                    array("company" => "toll","product" => "priority","fuel" => "33.19","extra" => "0"),
                    array("company" => "toll","product" => "ipec","fuel" => "21.3","extra" => "0"),
                    array("company" => "toll","product" => "pallets","fuel" => "37.97","extra" => "0"),
                    array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                    array("company" => "couriers_please","product" => "couriers_please","fuel" => "25.2","extra" => "7.9"),
                    array("company" => "sendle","product" => "sendle","fuel" => "4.05","extra" => "0"),
                    array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                    array("company" => "allied_express","product" => "sameday_local","fuel" => "15.9","extra" => "0"),
                    array("company" => "allied_express","product" => "interstate","fuel" => "21.9","extra" => "0"),
                    array("company" => "border_express","product" => "border_express","fuel" => "NA","extra" => "0"),
                    array("company" => "direct_freight","product" => "direct_freight","fuel" => "NA","extra" => "0"),
                    ),
                "09" =>array(
                    array("company" => "australia_post","product" => "australia_post","fuel" => "10.8","extra" => "0"),
                    array("company" => "australia_post","product" => "startrack","fuel" => "10.8","extra" => "0"),
                    array("company" => "aramex","product" => "myfastway","fuel" => "12","extra" => "0"),
                    array("company" => "toll","product" => "priority","fuel" => "33.19","extra" => "0"),
                    array("company" => "toll","product" => "ipec","fuel" => "18.5","extra" => "0"),
                    array("company" => "toll","product" => "pallets","fuel" => "29.55","extra" => "0"),
                    array("company" => "toll","product" => "air_express","fuel" => "12.3","extra" => "0"),
                    array("company" => "couriers_please","product" => "couriers_please","fuel" => "25.2","extra" => "10.5"),
                    array("company" => "sendle","product" => "sendle","fuel" => "6.85","extra" => "0"),
                    array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                    array("company" => "allied_express","product" => "sameday_local","fuel" => "15.9","extra" => "0"),
                    array("company" => "allied_express","product" => "interstate","fuel" => "21.9","extra" => "0"),
                    array("company" => "border_express","product" => "border_express","fuel" => "NA","extra" => "0"),
                    array("company" => "direct_freight","product" => "direct_freight","fuel" => "NA","extra" => "0"),
                ),
                "10" =>array(
                    array("company" => "australia_post","product" => "australia_post","fuel" => "11.3","extra" => "0"),
                    array("company" => "australia_post","product" => "startrack","fuel" => "11.3","extra" => "0"),
                    array("company" => "aramex","product" => "myfastway","fuel" => "11.3","extra" => "0"),
                    array("company" => "toll","product" => "priority","fuel" => "33.2","extra" => "0"),
                    array("company" => "toll","product" => "ipec","fuel" => "19.4","extra" => "0"),
                    array("company" => "toll","product" => "pallets","fuel" => "31.9,"extra" => "0"),
                    array("company" => "toll","product" => "air_express","fuel" => "14.15","extra" => "0"),
                    array("company" => "couriers_please","product" => "couriers_please","fuel" => "25.2","extra" => "10.6"),
                    array("company" => "sendle","product" => "sendle","fuel" => "6.85","extra" => "0"),
                    array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "27"),
                    array("company" => "allied_express","product" => "sameday_local","fuel" => "16.9","extra" => "0"),
                    array("company" => "allied_express","product" => "interstate","fuel" => "21.9","extra" => "0"),
                    array("company" => "border_express","product" => "border_express","fuel" => "NA","extra" => "0"),
                    array("company" => "direct_freight","product" => "direct_freight","fuel" => "NA","extra" => "0"),
                ),
               "11" =>array(
                    array("company" => "australia_post","product" => "australia_post","fuel" => "9.6","extra" => "0"),
                    array("company" => "australia_post","product" => "startrack","fuel" => "9.6","extra" => "0"),
                    array("company" => "aramex","product" => "myfastway","fuel" => "11.3","extra" => "0"),
                    array("company" => "toll","product" => "priority","fuel" => "33.19","extra" => "0"),
                    array("company" => "toll","product" => "ipec","fuel" => "19.4","extra" => "0"),
                    array("company" => "toll","product" => "pallets","fuel" => "31.93","extra" => "0"),
                    array("company" => "toll","product" => "air_express","fuel" => "0","extra" => "0"),
                    array("company" => "couriers_please","product" => "couriers_please","fuel" => "25.2","extra" => "10.6"),
                    array("company" => "sendle","product" => "sendle","fuel" => "7.05","extra" => "0"),
                    array("company" => "hunter_express","product" => "hunter_express","fuel" => "22","extra" => "0"),
                    array("company" => "allied_express","product" => "sameday_local","fuel" => "18.9","extra" => "0"),
                    array("company" => "allied_express","product" => "interstate","fuel" => "27.9","extra" => "0"),
                    array("company" => "border_express","product" => "border_express","fuel" => "NA","extra" => "0"),
                    array("company" => "direct_freight","product" => "direct_freight","fuel" => "22","extra" => "0"),
                ),
               "12" =>array(
                    array("company" => "australia_post","product" => "australia_post","fuel" => "10.2","extra" => "0"),
                    array("company" => "australia_post","product" => "startrack","fuel" => "10.2","extra" => "0"),
                    array("company" => "aramex","product" => "myfastway","fuel" => "10.2","extra" => "0"),
                    array("company" => "toll","product" => "priority","fuel" => "33.19","extra" => "0"),
                    array("company" => "toll","product" => "ipec","fuel" => "21.8","extra" => "0"),
                    array("company" => "toll","product" => "pallets","fuel" => "32.53","extra" => "0"),
                    array("company" => "toll","product" => "air_express","fuel" => "0","extra" => "0"),
                    array("company" => "couriers_please","product" => "couriers_please","fuel" => "25.2","extra" => "10.6"),
                    array("company" => "sendle","product" => "sendle","fuel" => "7.05","extra" => "0"),
                    array("company" => "hunter_express","product" => "hunter_express","fuel" => "20","extra" => "0"),
                    array("company" => "allied_express","product" => "sameday_local","fuel" => "15.9","extra" => "0"),
                    array("company" => "allied_express","product" => "interstate","fuel" => "21.9","extra" => "0"),
                    array("company" => "border_express","product" => "border_express","fuel" => "NA","extra" => "0"),
                    array("company" => "direct_freight","product" => "direct_freight","fuel" => "NA","extra" => "0"),
                )
             ));
echo json_encode($array);
